name: Publish to Maven

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-11, windows-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Configure Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Cache Konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Publish MacOS Artifacts
        if: matrix.os == 'macos-11'
        run: ./gradlew publishAllPublicationsToMavenRepository

      - name: Publish Windows Artifacts
        if: matrix.os == 'windows-latest'
        run: ./gradlew publishMingwX64PublicationToMavenRepository publishMingwX86PublicationToMavenRepository

env:
  ORG_GRADLE_PROJECT_repositoryUsername: ${{ secrets.ORG_GRADLE_PROJECT_repositoryUsername }}
  ORG_GRADLE_PROJECT_repositoryPassword: ${{ secrets.ORG_GRADLE_PROJECT_repositoryPassword }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }}
