name: Test pull request

on:
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Configure Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Cache Konan
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Build and Test
        run: ./gradlew build
